### ISSUE TITLE
Scenario bundles: Output datasets render weirdly

### ISSUE THREAD

**Issue by han-f** [OpenEnergyPlatform/oeplatform#1473]
## Description of the issue

I added an output dataset for the WAM scenario for this factsheet: https://openenergy-platform.org/scenario-bundles/id/95a65aca-6915-b64a-cac7-3831c12885b4

![grafik](https://github.com/OpenEnergyPlatform/oeplatform/assets/36844029/fa43133d-3cd7-4a22-80a0-384cbf6514e3)

It reads wrongly and shows more than only the title of the dataset, i.e. it should only be rendered as: Rahmendaten für den Projektionsbericht 2023 (Datentabelle) - as it does for the WEM scenario (this was already existing before the new release). 

## Steps to Reproduce
1. Add a dataset to a scenario
2.
3.

## Ideas of solution

Describe possible ideas for solution and evaluate advantages and disadvantages.

## Context and Environment
* Version used: 
* Operating system: 
* Environment setup and (python) version: 

## Workflow checklist
- [ ] I am aware of the workflow in [CONTRIBUTING.md](https://github.com/OpenEnergyPlatform/oeplatform/blob/develop/CONTRIBUTING.md)

**Comment by adelmemariani** [comment]
Yes, you are right. sorry, the script was reading the tags together with the name of the dataset. I fixed it. The issue will be solved in the next Hotfix release. Thank you, I appreciate your attention.

**Comment by adelmemariani** [comment]
@han-f Done! Please check if everything works. The full name of this dataset is `Rahmendaten für den Projektionsbericht 2023 (Datentabelle) (deutscher_projektionsbericht2023_rahmendaten)` in the list [here](https://openenergy-platform.org/dataedit/view/scenario?query=Rahmendaten+). As the `(deutscher_projektionsbericht2023_rahmendaten)` is there in the name, it is also shown in the bundles.

**Comment by han-f** [comment]
Thanks @adelmemariani. After refreshing it still renders the same for me. Attached a screenshot, including how it is rendered for the scenario (WEM) for which I already had it input prior to the new release:

![grafik](https://github.com/OpenEnergyPlatform/oeplatform/assets/36844029/770b9473-b4d1-4ec8-ac97-0354fff07998)

**Comment by han-f** [comment]
I think something changed between the current and previous release. I now added a dataset here, too and as you can see the previously added ones render as I would expect, only the one added today includes also tags etc. 

![grafik](https://github.com/OpenEnergyPlatform/oeplatform/assets/36844029/a37057ad-7d79-4c58-84b1-836b790fb149)

**Comment by adelmemariani** [comment]
> Thanks @adelmemariani. After refreshing it still renders the same for me. Attached a screenshot, including how it is rendered for the scenario (WEM) for which I already had it input prior to the new release:

I think to fix this issue, the bundle should be updated by first removing the wrong field and then adding it again.

> Would it be possible to revert back to how it previously worked?

I updated the bundle, and it shows the correct fields. It could be related to a caching problem.

**Comment by jh-RLI** [comment]
As far as i understand this is solved and requred the user to read all dataset? I will close this issue please reopen if it persists.

**Comment by han-f** [comment]
For me even after removing everything from the cache I still see the weird names:
* upper: how it should display (and was entered a "long time ago")
* lower: how it displays after some update, not so long ago

![grafik](https://github.com/OpenEnergyPlatform/oeplatform/assets/36844029/12423118-ef8c-475d-bddd-3d9b62a06941)

**Comment by jh-RLI** [comment]
> I think to fix this issue, the bundle should be updated by first removing the wrong field and then adding it again.

Have you tried removing entires and then adding them again? As far as I understand @adelmemariani, this is the only way to fix this for existing entries as they are not updated automatically.

**Comment by jh-RLI** [comment]
related to https://github.com/OpenEnergyPlatform/oeplatform/issues/1540

**Comment by jh-RLI** [comment]
The bundles now use the same "human-readable" name that is visible when we list the tables on the topic pages. So far there is no migration script that updates previous entries in the OEKG, and even if the metadata and name change, the name of the input/output dataset available in the OEKG is not updated. A related issue is that if someone deletes a table resource that is linked in the scenario, it will not be removed from the OEKG.

**Comment by jh-RLI** [comment]
I will create a new problem related to the additional issues I described above.
