### ISSUE TITLE
toep: visualisation data shown seems to not match data in tables on OEP (for some cases)

### ISSUE THREAD

**Issue by han-f** [OpenEnergyPlatform/oeplatform#1847]
## Description of the issue

For example: DE Data from 2021 projections, see screenshots, do not match the data in the tables of the OEP. This is a critical issue, if we want to release the projection visualisation.

Example: WEM scenario DE for 2025. (Same holds true also for Greece, and probably other countries).  

OEP: 
![grafik](https://github.com/user-attachments/assets/3325e36a-6bc5-42df-b5fa-e4f889995f8d)

toep:
![grafik](https://github.com/user-attachments/assets/92d0b081-09a6-4b37-9f02-da2075471bab)

## Steps to Reproduce

1. Select WEM for 2021 and 2023 tables (see screenshots for names) on toep visualisation
2. Select the same on OEP and filter 
3. Compare the data 

## Ideas of solution

Describe possible ideas for solution and evaluate advantages and disadvantages.

## Context and Environment

- Version used:
- Operating system:
- Environment setup and (python) version:

## Workflow checklist

- [ ] I am aware of the workflow in [CONTRIBUTING.md](https://github.com/OpenEnergyPlatform/oeplatform/blob/develop/CONTRIBUTING.md)

cc @wingechr

**Comment by han-f** [comment]
same holds true for other selections of data too, see screenshots:
OEP:
![grafik](https://github.com/user-attachments/assets/5d80a4f2-4e0c-41f7-87a7-ce5efad87583)

TOEP:
![grafik](https://github.com/user-attachments/assets/efc06686-39ec-4bf4-a21d-fc4fde33cadc)

**Comment by adelmemariani** [comment]
Thank you @han-f for reporting this bug. I fixed this issue on the toep sever. It should now look like below:

 
![Screenshot 2024-09-18 at 13 45 52](https://github.com/user-attachments/assets/91a15af8-1277-4b88-9d3f-b28caef804aa)

**Comment by jh-RLI** [comment]
Hm, I think the values are still strange, aren't they? For example, the value for Germany is high in 2021 and very low in 2023. That would be a drastic change.

**Comment by adelmemariani** [comment]
Thanks a lot @jh-RLI , I fixed it:

  
![Screenshot 2024-09-18 at 14 36 26](https://github.com/user-attachments/assets/6bbbfa66-bfe1-4beb-801b-ff75f0a8d60a)

**Comment by han-f** [comment]
I still see the different values, do I need to make an extra refresh?

![grafik](https://github.com/user-attachments/assets/f420903a-039c-4cb4-ae43-5d9152ab2195)

**Comment by adelmemariani** [comment]
I recently, fixed the issue with the static data, maybe in the mean time you tested it.  I see the chart as following:

![Screenshot 2024-09-18 at 14 54 18](https://github.com/user-attachments/assets/96a5c522-b669-414d-acd4-de4c1c964707)

**Comment by jh-RLI** [comment]
I also just checked and i had to refresh the page without browser cache. I think this is the issue for you @han-f 

![image](https://github.com/user-attachments/assets/10a183e6-8d2b-42a7-88d7-50e1274ca5ff)

For some reason, the width of the chart is now smaller than before, resulting in an even smaller chart, but this is not so relevant. I think the data related bug is solved now, but we should check other cases as well. For example, I'm not sure what happens with 3 tables. Also, it would be great to see the submission years, but as I said a while ago, we don't really have the data available for that, possibly in the metadata. But for the demo next week that seems to be found, what do you think?

**Comment by adelmemariani** [comment]
@jh-RLI , I don't see the smaller chart. Could you check if it is solved when you change the window size or the browser?

**Comment by jh-RLI** [comment]
Yes, correct it depends on the window size. Then it is okay for now :)

**Comment by jh-RLI** [comment]
@han-f @wingechr 
I'll use this issue to point out all the issues that have been fixed, not just this particular one. Especially the ones we saw during our meeting @han-f. Thanks for the implementation @adelmemariani !

I checked a few things today and also checked that the data is correctly retrieved (for 2 data points at least) and it seems to me that it is much more stable again, the feedback was very valuable.  

I'll do the release for OEP v1.0.0 until monday (it's time for it, even if there are still issues), then we can check everything with the updated bundles / scenarios on the OEP and see how things work there. I also think there is still room for a smaller bugfix release next Monday if we find more very urgent bugs. So please check everything on Monday if possible.

**Comment by jh-RLI** [comment]
- [ ] remove from the drop down menu for the output dataset the name of the scenario, e.g. ‘WAM:...’ if that is possible. Hannah was confused because it looks to her like we are now selecting the scenario twice.

- [ ] sort the drop down menu of sectors by number and also by number and letter so that 1. 1.a.1 1.a.2.b 2. 2.a.1 ..... and so on

- [ ] it would be very nice if the scenario year 2025 could be selected first. I think for our case study we always have this year and it is a better starting year than 2015 because there are more data points.

Now for the issues with the data after initially selecting some tables/scenarios and then changing that selection and hitting submit again

- [ ] if you select a different option from the filter dropdown, the previously selected year will remain selected but will show data from 2015. You need to select a different year and then select 2025 again to see the data.

- [ ] when adding a table to the current selection and submitting, the data is [incorrect.It](http://incorrect.it/) appears that the same data is displayed twice.

- [ ] If you change the dropdown selection for the scenario after changing selection from e.g. WEM to WAM, the data is also not correct. It also seems that not the WAM scenario is selected, but some earlier data.
